package services





































































































































}	})		})			})				Size: 10,			m.Text(data.Description, props.Text{		m.Col(12, func() {	m.Row(10, func() {	})		})			})				Size:  11,				Style: consts.Italic, // Itálico na empresa			m.Text(data.Company, props.Text{		m.Col(12, func() {	m.Row(8, func() {		})		})			})				Size:  10,				Align: consts.Right,			m.Text(data.DateRange, props.Text{		m.Col(4, func() {		})			})				Size:  12,				Style: consts.Bold,			m.Text(data.Role, props.Text{		m.Col(8, func() {	m.Row(10, func() {func renderExperience(m pdf.Maroto, data models.ExperienceBlockData) {}	})		})			})				VerticalPadding: 1.0,				Extrapolate:     false,				Align:           consts.Left,				Size:            11,			m.Text(data.Text, props.Text{		m.Col(12, func() {	m.Row(10, func() {func renderText(m pdf.Maroto, data models.TextBlockData) {}	})		})			})				Align: consts.Center,				Style: consts.Normal,				Size:  10,			m.Text(data.Address, props.Text{		m.Col(12, func() {	m.Row(10, func() {	})		})			})				Align: consts.Center,				Style: consts.Normal,				Size:  10,			m.Text(contact, props.Text{			contact := fmt.Sprintf("%s | %s | %s", data.Email, data.Phone, data.Link)		m.Col(12, func() {	m.Row(10, func() {	})		})			})				Align: consts.Center,				Style: consts.Bold,				Size:  18,			m.Text(data.FullName, props.Text{		m.Col(12, func() {	m.Row(20, func() {func renderHeader(m pdf.Maroto, data models.HeaderBlockData) {}	return buffer.Bytes(), nil	}		return nil, err	if err != nil {	buffer, err := m.Output()	}		}			m.Line(5)		case "SPACER":			renderExperience(m, data)			}				return nil, fmt.Errorf("failed to unmarshal experience block: %w", err)			if err := json.Unmarshal(block.Content, &data); err != nil {			var data models.ExperienceBlockData		case "EXPERIENCE":			renderText(m, data)			}				return nil, fmt.Errorf("failed to unmarshal text block: %w", err)			if err := json.Unmarshal(block.Content, &data); err != nil {			var data models.TextBlockData		case "TEXT":			renderHeader(m, data)			}				return nil, fmt.Errorf("failed to unmarshal header block: %w", err)			if err := json.Unmarshal(block.Content, &data); err != nil {			var data models.HeaderBlockData		case "HEADER":		switch block.Type {	for _, block := range blocks {	m.SetPageMargins(20, 10, 20)	m := pdf.NewMaroto(consts.Portrait, consts.A4)func (s *PDFService) GeneratePDF(blocks []models.CVBlock) ([]byte, error) {}	return &PDFService{}func NewPDFService() *PDFService {type PDFService struct{})	"github.com/tacio/parseit-backend/internal/models"	"github.com/johnfercher/maroto/pkg/props"	"github.com/johnfercher/maroto/pkg/pdf"	"github.com/johnfercher/maroto/pkg/consts"	"fmt"	"encoding/json"	"bytes"import (package services